spring:
  application:
    name: euraka-server

server:
  port: 8761
eureka:
  client:
    service-url:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/euraka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost



